### ISSUE TITLE
This action is unauthorized

### ISSUE THREAD

**Issue by foRsxs** [opcodesio/log-viewer#218]
Hi! 

if I added to AuthServiceProvider 

```
Gate::define('viewLogViewer', function (User $user) {
            return $user->isAdmin();
        });
```

LogViewer is load and I can see page, but on left side i got message Request failed with status code 403: This action is unauthorized. No log files were found. It seems like can't load log files

```
"message": "This action is unauthorized.",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException",
```

In another project with version 1.8 all working is good

**Comment by arukompas** [comment]
Hey @foRsxs , what does your `api_middleware` configuration option look?

```php
    /*
    |--------------------------------------------------------------------------
    | Log Viewer API middleware.
    |--------------------------------------------------------------------------
    | Optional middleware to use on every API request. The same API is also
    | used from within the Log Viewer user interface.
    |
    */

    'api_middleware' => [
        \Opcodes\LogViewer\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
        \Opcodes\LogViewer\Http\Middleware\AuthorizeLogViewer::class,
    ],
```

Make sure that the `\Opcodes\LogViewer\Http\Middleware\EnsureFrontendRequestsAreStateful::class` middleware is there because otherwise the frontend will be unauthenticated.

**Comment by foRsxs** [comment]
I'm not used config for log-viewer, but now I did publish vendor and config cache (with remove all cache files)

` /*
    |--------------------------------------------------------------------------
    | Log Viewer route middleware.
    |--------------------------------------------------------------------------
    | Optional middleware to use when loading the initial Log Viewer page.
    |
    */

    'middleware' => [
        'web',
        \Opcodes\LogViewer\Http\Middleware\AuthorizeLogViewer::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Log Viewer API middleware.
    |--------------------------------------------------------------------------
    | Optional middleware to use on every API request. The same API is also
    | used from within the Log Viewer user interface.
    |
    */

    'api_middleware' => [
        \Opcodes\LogViewer\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
        \Opcodes\LogViewer\Http\Middleware\AuthorizeLogViewer::class,
    ],`

But it's not help (

If I remove Gate from auth provider - everything works fine.
I don't know why api log-viewer not working with gate

**Comment by arukompas** [comment]
@foRsxs check the network tab in the browser for the files/logs request. Make sure the cookies are sent over and not blocked for any reason. Maybe you can share the screenshot of the Network tab and the frontend request made? With the headers and stuff.

**Comment by foRsxs** [comment]
> @foRsxs check the network tab in the browser for the files/logs request. Make sure the cookies are sent over and not blocked for any reason. Maybe you can share the screenshot of the Network tab and the frontend request made? With the headers and stuff.

Seems issue is in auth with cookie, but cookies are sent

![image](https://user-images.githubusercontent.com/18087400/227266541-45b4080d-2fef-4f77-8a89-04674d38cc65.png)
![image](https://user-images.githubusercontent.com/18087400/227267047-02e5719a-5252-48ab-b007-7434214fc234.png)

**Comment by foRsxs** [comment]
Issue was in cookie. If local env without https u have to do this 

`'secure' => env('SESSION_SECURE_COOKIE', false)`

  in your config/session.php, don't forget config:cache

**Comment by trbsi** [comment]
It looks fine for me

![Screenshot_1](https://user-images.githubusercontent.com/3958715/228470975-dec8a82a-ac0f-4b1a-a4e0-0a6d7ca921ee.png)
![Screenshot_2](https://user-images.githubusercontent.com/3958715/228470978-02274a64-d757-4888-a7a5-b5b233195571.png)

**Comment by arukompas** [comment]
Hey @trbsi sorry, but the images are all cropped :/ can't see the end of the cookie where the warnings usually appear.

Either way, are you viewing the Log Viewer through an iframe maybe?

I can also see the the XHR request is HTTPS. Is the original page also loaded over HTTPS?

And lastly, what's the value of `config('session.secure')`?

**Comment by trbsi** [comment]
Thanks for responding. I installed another solution. Usually I would debug this, but right now I don't have a time for it

**Comment by RenoLooijmans** [comment]
I am experiencing the same issue.

Tried debugging it using the snippet below, but I can't wrap my head around it why it is not working... I installed a recent and clean install of Log Viewer. Api middleware is present in the log viewer config.

`
Gate::define('viewLogViewer', static function (?User $user) {
            if(request()->is('*api*')) {
                dd(request()->user());
            }
            return ! is_null($user) && $user->isAdministrator();
        });
`

returns the following:
![image](https://user-images.githubusercontent.com/73367951/229939900-3fa54ae4-f7e9-4227-9c87-37d5a727f811.png)

config('session.secure') returns false.

Request headers are:

![image](https://user-images.githubusercontent.com/73367951/229940859-81f0b8b3-01bb-4830-99dd-4e61d2b1d231.png)

![image](https://user-images.githubusercontent.com/73367951/229940980-e2017909-02aa-4f47-be9c-c365ae13f92c.png)

Doesn't work on https either.

Any idea?

**Comment by arukompas** [comment]
Hey @RenoLooijmans , I know Laravel can be very sensitive to how you define and type-hint the params in Gate callbacks.

1. What Laravel version is this? So I can test using that version as well.
2. Can you try changing the `?User` type-hint to just `mixed` ?

```php
Gate::define('viewLogViewer', static function (mixed $user) {
    if(request()->is('*api*')) {
        dd(request()->user());
    }

    return ! is_null($user) && true;
});
```

3. If above doesn't help, can you also dump some debug data like this:

```php
use Illuminate\Support\Facades\Route;

//...

Gate::define('viewLogViewer', static function (mixed $user) {
    if(request()->is('*api*')) {
        $route = Route::getCurrentRoute();
        dd([
            'url' => $route->uri(),
            'session_id' => session()->getId(), // let's make sure the session ID is the same as the one from the initial page load
            'middleware' => $route->middleware(),
            'user_id' => request()->user()?->id,
            'user_id_from_gate_callback_params' => $user?->id,
        ]);
    }

    dump(['session_id' => session()->getId()]);

    return ! is_null($user) && true;
});
```

This gives me a result like this:
<img width="1265" alt="Screenshot 2023-04-05 at 08 39 27" src="https://user-images.githubusercontent.com/8697942/229990991-16317081-7a3e-4304-9e40-57ca3627e87f.png">

Note how the session ID is the same on both requests, meaning it's persisted correctly. And that's the job of the middleware which should also show up for you as well.

Let me know what your result looks like!

**Comment by RenoLooijmans** [comment]
Hi Arunas,

Thanks for your quick reply.

Hereby my answers.

1. Laravel Framework 9.52.5
2. Also returns null, unfortunately..
3. Session ID for the initial load is different than the one from the API, which is strange...!
![image](https://user-images.githubusercontent.com/73367951/230219307-d41634c3-ecec-409e-9d6f-62860cbca685.png)

Any idea what I could be missing?

**Comment by RenoLooijmans** [comment]
Okay so I spend some time debugging my setup, and finally I got around fixing it.

So, I came across two issues.

- Firstly, my sanctum stateful domain was incorrect. Since I have not used stateful requests before, I was not aware this would be the issue. I have changed this accordingly.
- Secondly, the 'fromFrontend' method in 'EnsureFrontendRequestsAreStafeful' middleware was not working correctly in my situation. It compares the referer with the domains in the 'sanctum.stateful' config entry, or defaultStateDomains-method as backup. In my case, the referer returned 'http://mydomain.local/log-viewer' (as my path for log-viewer in the config is 'log-viewer'). This is being transformed to 'mydomain.local/log-viewer/', and then compared with entries in the 'sanctum.stateful' config value. These values are being transformed to entries like 'mydomain.local/*'. In the end 'mydomain.local/log-viewer/' is compared with 'mydomain.local/*', which returns false. The quickest fix was to include the exact path to the 'sanctum.stateful' domains list. So in the end my 'sancum.stateful' looked like this:

![image](https://user-images.githubusercontent.com/73367951/231003239-4ad8fd7b-8fe1-4158-9871-c347f75802fa.png)

To be clear, this did NOT work.
![image](https://user-images.githubusercontent.com/73367951/231003366-036b9788-5dd2-4e1e-9025-9b92647b9b1d.png)

I probably missed something in the docs, but this was my fix. I think the 'fromFrontend'-method should not perform an EXACT compare, but should check whether the referer matches a domain or certain path, with an asterisk being the wildcard.

**Comment by RenoLooijmans** [comment]
You're all right ;-)

And I totally missed that part... Apologies, I really wasn't aware of this piece...

Looks like this is solved - thanks!

**Comment by foRsxs** [comment]
@arukompas I found new problem) If we use in config url like (https://example.com), but in browser open url with www (https://www.example.com/log-viewer) all requests in API will be with error 403

**Comment by hamza094** [comment]
I've tried everything mentioned above but still encounter the following error: 'Request failed with a status code of 403: This action is unauthorized.
 I'm using Laravel 10 with the following packages:

laravel/sanctum version 3.2
opcodesio/log-viewer version 3.0"

If you have a moment, could someone please provide guidance on how to resolve this issue? Your help would be greatly appreciated.

,

**Comment by arukompas** [comment]
@hamza094 hey, it's usually due to middleware or gate policies being set up incorrectly.

Could you please share:
- how you've defined the Gate for viewing the Log Viewer (or if you haven't)
- config/log-viewer.php contents
- app/Http/Kernel.php contents (in case you have modified the default web middleware group)
- are you using the default app/Models/User class to represent authenticated user?

Hopefully I'll be able to help after that :)

**Comment by hamza094** [comment]
in AppServiceProvider boot method

`   LogViewer::auth(function ($request) {
        return $request->user()
            && in_array($request->user()->email, [
                'ressie03@example.net',
            ]); 
        });
`

in config/log-viewer.php
```
 'middleware' => [
        'web',
        /*\Opcodes\LogViewer\Http\Middleware\AuthorizeLogViewer::class,*/
    ],
    
     'api_middleware' => [
        \Opcodes\LogViewer\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
        \Opcodes\LogViewer\Http\Middleware\AuthorizeLogViewer::class,
    ],
```
in Kernel.php

```
 'api' => [
             'throttle:60,10',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
            \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
        ],    
```
I'm experiencing an issue where the authentication user is null in LogViewer, even though the authentication works fine throughout the rest of my application

**Comment by arukompas** [comment]
@hamza094 , I just had a similar issue myself, and the solution was to correctly define the Sanctum stateful domains ([see here](https://laravel.com/docs/10.x/sanctum#spa-configuration)).

`www.example.com` is different from `example.com`, and in my case I had the wrong one defined, which is why my Log Viewer API calls were not authenticated. Sanctum refuses to authenticate API requests if they come from a different domain.

Try changing the `app.url` or `sanctum.stateful` configuration to see if it works.

**Comment by yoeriboven** [comment]
For now my issue was solved by removing `www` from `APP_URL`.

**Comment by cambur** [comment]
> For now my issue was solved by removing www from APP_URL.

Exactly the same for me

**Comment by stephenstack** [comment]
Same here it seems, APP_URL must match the URL being called to open log viewer.

**Comment by N3OGeorgy** [comment]
There is a solution if the APP_URL in .env does not match the URL /log-viewer is being called?

**Comment by arukompas** [comment]
@N3OGeorgy correct, although you can also use the more-recently-added Log Viewer-specific environment variable:

comma-separated list of domains allowed to communicate with the Log Viewer:
```env
LOG_VIEWER_API_STATEFUL_DOMAINS=mysubdomain.domain.com,otherdomain.com
```

**Comment by N3OGeorgy** [comment]
@arukompas Good to know, thank you. It's easy to miss it actually. I didn't find any information about it in the docs. In config file is also not documented.
Maybe something could be added like the info found on [https://github.com/laravel/sanctum/blob/4.x/config/sanctum.php](url)

**Comment by arukompas** [comment]
Added docs here:
https://log-viewer.opcodes.io/docs/3.x/configuration/route-and-domain#production-domains
